### ISSUE TITLE
Develop Branch - Need to Investigate with Py3.6

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-chatops#121]
### Environment
* Python version:  3.6
* Nautobot version:  1.x
* nautobot-plugin-chatops version: Develop branch

### Steps to Reproduce
1. Get the latest development instance
2. Execute `invoke debug` and spin up an ngrok instance
3. Attempt to execute `/nautobot` commands, not successful
4. Update to use Py3.7 and latest celery, everything works fine

### Expected Behavior

Commands to work

### Observed Behavior

NGROK shows the commands coming in and 200 OK, but the Slack bot testing did not work.

**Comment by jvanderaa** [comment]
Need to investigate if this is an issue or not. Currently am not recommending installation of ChatOps from Git at this time.

**Comment by smk4664** [comment]
At this time, we have officially dropped support for Py3.6
