### ISSUE TITLE
Hidden message option causes error when receiving a response

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot-plugin-chatops#127]
### Environment
* Nautobot version:  1.2.7
* nautobot-plugin-chatops version:  1.6.0

### Steps to Reproduce
1. Enable settings `"send_all_messages_private": True` in plugin configuration
2. Type any `/nautobot` command in Slack
3. Response from Slack is an error message
![image](https://user-images.githubusercontent.com/14314517/157216761-5ea6ff23-10df-401a-99ee-94fb14586399.png)

### Expected Behavior
Data should be returned 'normally' (via ephemereal (hidden) message).

### Observed Behavior
This issue happened only when private message option is enabled.

**Comment by ubajze** [comment]
The problem in `1.7.0` is described in #132 .

**Comment by jvanderaa** [comment]
Fixed in #133
