### ISSUE TITLE
Send Large Table to Assigned User

### ISSUE THREAD

**Issue by justinjeffery-ipf** [nautobot/nautobot-plugin-chatops#141]
### Environment
* Nautobot version:  1.3.3
* nautobot-plugin-chatops version:  1.8.0

### Proposed Functionality

Allow sending a table to only an assigned  user.

send_large_table:
`
...
self.send_snippet(table.draw(), title=title)
`

`send_snippet(self, text, title=None, ephemeral=None)`

**Comment by jvanderaa** [comment]
Does the `send_all_messages_private` setting work for this?

**Comment by justinjeffery-ipf** [comment]
I need this for a specific use case in the chatops-ipfabric.

Menu Prompt is visible to only assigned user however the table is being sent to all users.

![image](https://user-images.githubusercontent.com/92743314/176705164-2035cb24-f9c8-4aac-a07c-5dd60f3ea840.png)

**Comment by jvanderaa** [comment]
Yeah, the menu is set to that specifically. The setting mentioned was built for just this.

**Comment by jvanderaa** [comment]
Although that would be every command result, changing the entire bot behavior. 

This may be a setting that could be set up on the chatops-ipfabric bot with some optional settings. Can also be prompted for.

**Comment by jvanderaa** [comment]
I think I see there. I think that makes sense.

**Comment by justinjeffery-ipf** [comment]
Ok thanks, closing ticket and implementing a new way.
