### ISSUE TITLE
Mattermost menu cancel button processes as 401

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot-plugin-chatops#16]
### Environment
* Python version:   3.8.5
* Nautobot version:   1.0.0b2
* nautobot-plugin-chatops version:   1.0.1

In Mattermost, if you run any command that prompts you with a menu selection, for example to either to select a value or a filter, but you click the cancel button instead, there is no error displayed to the user but the backend Django server processes it as a 401 error.

`[12/Mar/2021 15:26:46] "POST /api/plugins/chatops/mattermost/interaction/ HTTP/1.1" 401 0`

Other selections are processed correctly.
This action in other chat ops programs are processed correctly when the cancel button is clicked.

Slack example:
`[12/Mar/2021 15:32:12] "POST /api/plugins/chatops/slack/interaction/ HTTP/1.1" 200 0`

### Steps to Reproduce
1. In Mattermost, run the command `/nautobot get-devices` (or any command that prompts with a menu selection box)
2. Click "Cancel"
3. Observe Django logs on backend Nautobot server

### Expected Behavior

The server to process the request as a 200 OK.

### Observed Behavior

The server processes the request as a 401.  In Ngrok, the HTTP request shows as:

`POST /api/plugins/chatops/mattermost/interaction/   401 Missing Command Token`

**Comment by smk4664** [comment]
I will take this one up and investigate.

**Comment by jvanderaa** [comment]
@smk4664 assigned.

**Comment by smk4664** [comment]
Finally fixing this today. Going to be out in the 1.5.0 release.
