### ISSUE TITLE
Error filtering interface connections by region

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot-plugin-chatops#17]
### Environment
* Python version:   3.8.5
* Nautobot version:   1.0.0b2
* nautobot-plugin-chatops version:   1.0.1

There is an error across all supported chatops platforms if you try to filter by region for the command `/nautobot get-interface-connections`, but no regions are configured in Nautobot.  This also occurs if regions are configured, but no sites are assigned a region.

NOTE: If a region is configured, and a site is assigned to a region, this bug does _not_ trigger even if there are no interfaces connections in that region.

Each chatops program gives different responses:

- MS Teams - untested
- Mattermost - Nothing happens
- Webex Teams - this message appears:

`If you're seeing this message, something went wrong`

- Slack - this message appears:

```
Sorry <user>, an error occurred :sob:
The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'internal_error'}
```

### Steps to Reproduce
1. Either way will trigger the bug here:
    1a. In Nautobot, verify no regions are configured
    1b. In Nautobot, verify no sites are assigned to any configured regions (regions can still be configured to trigger this bug)
2. In any chatops program, run command `/nautobot get-interface-connections`
3. In the initial filter box labeled "Select an interface connection filter", select "Region"

### Expected Behavior

A message or similar stating no regions are available to filter by
OR
Region to not even be a filterable option

### Observed Behavior

A workflow crash occurs, with some platforms responding with an error message, and others do not (see above for platform specific details)

**Comment by jvanderaa** [comment]
@matt852 is this still an issue?

**Comment by matt852** [comment]
@jvanderaa Yes.  I haven't had a chance to look into this yet.

**Comment by smk4664** [comment]
I will try to submit a PR for this soon.  I have an idea of how to return a good warning to the user.
