### ISSUE TITLE
Webex Teams: Error with too large an output

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot-plugin-chatops#2]
### Environment
* Python version:   3.8.5
* Nautobot version:   1.0.0b2
* nautobot-plugin-chatops version:   1.0.1

### Steps to Reproduce
1. Have over 200 devices in one site in the Nautobot DB
2. In Webex teams, run the "get-devices" command for that category
3. For device filter, select "Site"
4. Select the site with over 200 devices in it

### Expected Behavior

For get-devices, I expected the bot to return all devices in the site.

### Observed Behavior
Webex (not nautobot) returned an error, presumably because nautobot successfully generated the list of devices, but it was too large for Webex to handle.  The error is:

`An internal error occurred: [400] Bad Request - Unable to post message to room: Message length limited to 7439 characters before encryption and 10000 characters after encryption. [Tracking ID: ROUTER_604A552B-AD26-01BB-03BA-AC12FB2803BA]`

The Tracking ID changes each time.

Also note this exact same error occurs for similar commands.  For example, if you have too many circuits at one site, and run the "get-circuits" command, and filter by "All (no filter)"

**Comment by jvanderaa** [comment]
Good catch on the character length. There was something similar in the Slack dispatcher as well.

**Comment by matt852** [comment]
Please assign this to me
