### ISSUE TITLE
Rename Webex Teams -> Webex

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-chatops#24]
### Environment
* Python version:  N/A
* Nautobot version:  N/A
* nautobot-plugin-chatops version: 1.0.0

### Observed Behavior

Webex Teams has been renamed to just **Webex**. This may help the messaging to rename webex_teams work to just webex where applicable.

**Comment by matt852** [comment]
Please assign this to me.  I submitted PR #55 to address this issue.

**Comment by jvanderaa** [comment]
Closed by #55
