### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-plugin-chatops#38]
### Environment
* Nautobot version:  1.0b4
* nautobot-plugin-chatops version: 1.1.0

### Proposed Functionality

Please update the nautobot logo in this repo to be the square logo from the public slack channel.

**Comment by jvanderaa** [comment]
Clarification of this one? @nniehoff

**Comment by nniehoff** [comment]
@jvanderaa this is the logo I am looking for, obviously not a screenshot but you get the idea:

![Screen Shot 2021-04-26 at 7 24 14 AM](https://user-images.githubusercontent.com/14947575/116089773-69fa1380-a660-11eb-8c58-364150301f22.png)

**Comment by smk4664** [comment]
![image](https://user-images.githubusercontent.com/17092348/129796349-da0a9b45-763a-4927-966c-1dde53a84d41.png)
It looks like this issue can be closed.  The logo is now using the square logo.
