### ISSUE TITLE
Cleanup Pylint Messages

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot-plugin-chatops#50]
### Proposed Functionality
Currently we have most of the pylint settings ignored, we should fix what we can and ignore specific issues in the individual files and not globally.

### Use Case
New Developed code would standout when an exception was made or when it is not following pylint.

**Comment by jvanderaa** [comment]
Also move into pyproject.toml for the configuration.

**Comment by smk4664** [comment]
I will be moving them in my current PR, but not fixing issues.

**Comment by tanvimoharir** [comment]
Hello, I would like to work on this.
Thanks

**Comment by tanvimoharir** [comment]
Hi, I have looked into this and started working on it.
Please refer #51 
Let me know if I can continue with it or otherwise.
Thanks

**Comment by smk4664** [comment]
Go right ahead! Thank you for working on this!

**Comment by jvanderaa** [comment]
Thanks @tanvimoharir, long weekend here. I have added you as the assigned owner as well.

**Comment by tanvimoharir** [comment]
Hi,
I have the PR as a draft right now and I will mark it 'Ready for review' once I'm done with the changes and the build is also passing.
Please feel free to review it otherwise as well. (I am not able to add any reviewers)
Thanks

**Comment by tanvimoharir** [comment]
Please Refer #51 
(I'm not so sure about the changes done to pyproject.toml)

**Comment by smk4664** [comment]
Closed with PR #51
