### ISSUE TITLE
Command with 2 args both requiring quotes fail if both sets of quotes use double quotes.

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-plugin-chatops#52]
### Environment
* Python version:  3.8.5
* Nautobot version:  1.0.2
* nautobot-plugin-chatops version:  1.3.0

### Steps to Reproduce
1. Have two args for a command.  Example `/meraki get-switchports [org-name] [device-name]`
2. Both the args have spaces in them which now require the use of quotes around the arg names. Command example `/meraki get-camera-recent “Aspire Technology Partners, LLC.” "MV12 Staging Lab Cam1"`
3. Use double quotes around both arg names.

### Expected Behavior
The command runs as expected.

### Observed Behavior
Immediately the command fails with error.
==> /var/log/nautobot/nautobot.log <==
2021-05-27 16:53:15 ERROR No closing quotation

`/meraki get-camera-recent "Aspire Technology Partners, LLC." 'MV12 Staging Lab Cam1'` works
`/meraki get-camera-recent "Aspire Technology Partners, LLC." "MV12 Staging Lab Cam1"` doesn’t work
`/meraki get-camera-recent 'Aspire Technology Partners, LLC.' 'MV12 Staging Lab Cam1'`  also works.

Appears to be an issue with `parse_command_string` function.

**Comment by jeffkala** [comment]
If I implement dropdowns for both args everything works fine.

**Comment by smk4664** [comment]
Thanks for the report @jeffkala.  I added a test locally but cannot get this test to error, it could be the way that Slack is handling the quotes.  This may take a bit to fix.

**Comment by jvanderaa** [comment]
@jeffkala @smk4664 what is the status here?

**Comment by jeffkala** [comment]
@jvanderaa IIRC @smk4664 tried to get this to fail using tests with all different kinds of quote usage and it wouldn't fail in a test function, so more work needed to be done on it.  It's on my list to deep dive into it again now that i'm starting the OSRB process to get the Meraki chatops plugin moved to Nautobot org.

**Comment by jeffkala** [comment]
@jvanderaa @smk4664 I can no longer duplicate this, (no longer have access to the Aspire meraki instance) since the project ended.  Using our NTC instance I can't duplicate it, so wonder if it was the `,` in the name of the ORG that was causing some issues.
