### ISSUE TITLE
Migrate to Celery Worker

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-plugin-chatops#64]
### Environment
* Nautobot version:  1.1.0
* nautobot-plugin-chatops version:  1.x

### Proposed Functionality

The Chatops plugin should use Celery workers in Nautobot 1.1

### Use Case

RQ is being deprecated

**Comment by jvanderaa** [comment]
Any immediate thoughts on how to migrate gracefully?

**Comment by glennmatthews** [comment]
See https://github.com/nautobot/nautobot-plugin-device-onboarding/pull/18 for one possible approach.

**Comment by jvanderaa** [comment]
Are there any settings that can be imported to check on the current running version?

**Comment by glennmatthews** [comment]
Sure, `settings.VERSION` should have the Nautobot version.

**Comment by smk4664** [comment]
I will be taking on this issue today.
