### ISSUE TITLE
Automatically fix markdown links for slack

### ISSUE THREAD

**Issue by retnuh** [nautobot/nautobot-plugin-chatops#65]
Normal links in markdown are written like this [an example](http://example.com) i.e. `[an example](http://example.com)`.

However, Slack, for whatever reason, formats links like `<http://example.com|an example>`.  It would be nice if the `dispatcher.send_markdown` implementation for Slack automatically converted normal markdown link syntax into Slack syntax, so users could just write normal link syntax.

Bonus points for other dispatchers to notice other syntax and convert to whatever "native" syntax is!

**Comment by smk4664** [comment]
Slack has its own take on markdown... https://www.markdownguide.org/tools/slack/

But, this would be nice to have.

**Comment by jvanderaa** [comment]
This seems like we should add in a markdown to slack markdown converter. Definitely going to add this in as a feature enhancement.

**Comment by smk4664** [comment]
Given we already have functions for making text bold, we might go that route as it would allow easy support for all dispatchers.  https://github.com/nautobot/nautobot-plugin-chatops/blob/57cee364d461ba941062dba64942537b58ff07ea/nautobot_chatops/dispatchers/base.py#L234
