### ISSUE TITLE
Mattermost dispatcher prompt_for_text flaky

### ISSUE THREAD

**Issue by retnuh** [nautobot/nautobot-plugin-chatops#66]
### Environment
* Python version: 3.7
* Nautobot version:  1.0.3
* nautobot-plugin-chatops version:  1.3.1

### Steps to Reproduce
1.  Have a command workflow with two or more `dispatcher.prompt_for_text` calls
2. Run against a local mattermost instance
3. invoke the command a few times in mattermost, such that the prompts take place

### Expected Behavior
The prompts take place, in the order expected

### Observed Behavior
I am seeing the `prompt_for_text` command fail intermittently, even on the first command, almost certainly on two prompts in a row.  I see this in mattermost:

```
Malformatted requests: {"id":"interactive_message.decode_trigger_id.missing_data","message":"Trigger ID missing required data for interactive dialog.","detailed_error":"","request_id":"kyhrzqod4iynfd64kxn5sdwc3o","status_code":400}
```

And this in mattermost's docker logs:
```
{"level":"debug","ts":1626965190.1836636,"caller":"mlog/log.go:230","msg":"Trigger ID missing required data for interactive dialog.","path":"/api/v4/actions/dialogs/open","request_id":"kyhrzqod4iynfd64kxn5sdwc3o","ip_addr":"172.17.0.1","user_id":"s3fucxrozfdadfspy98ym8jdxe","method":"POST","err_where":"DecodeAndVerifyTriggerId","http_code":400,"err_details":""}
```

Intermittent, but reliably intermittent, if that makes sense.  I do not see the same behaviour in the dispatcher for slack.

**Comment by jvanderaa** [comment]
@smk4664 @matt852 any chance you can take a look at this one?

**Comment by smk4664** [comment]
@retnuh Is this happening against a local instance of Mattermost, or the Hosted Mattermost?  In the meantime, I will try to reproduce this issue on my local instance of Mattermost.

**Comment by retnuh** [comment]
Local version of mattermost, run via Docker.

**Comment by smk4664** [comment]
@retnuh Mind providing an example of how you're creating the `prompt_for_text`?  If you are trying to prompt for more than one entry at a time, you would want to use `multi_input_dialog`.

**Comment by smk4664** [comment]
Here is an example

`@subcommand_of("nautobot")
def multi_dialog(dispatcher, text1, text2, text3):
    """Test Multiple Prompts."""
    if not (text1 and text2):
        # If the user just invoked "nautobot multi-dialog" with no parameters, all of the params will be None.
        # If the user ran a partial command "nautobot multi-dialog text1", the other params will be None.
        # If the user submitted the dialog but left some fields blank, they will be "" and we should complain
        if text1 == "":
            subnet = None
            dispatcher.send_warning("Text1 must be specified")
        if text2 == "":
            dispatcher.send_warning("Text2 must be specified")

        dispatcher.multi_input_dialog(
            "nautobot",
            "multi-dialog",
            "Input Form", # limited to 80 characters
            [
                {"type": "text", "label": "Text1", "default": "text1"},
                {"type": "text", "label": "Text2", "default": "text2"},
            ],
        )
        return False
    
    dispatcher.send_blocks(
        [
            *dispatcher.command_response_header(
                "nautobot",
                "multi-dialog",
                [("Text 1", text1), ("Text 2", text2)],
                "text test",
                nautobot_logo(dispatcher),
            ),
            dispatcher.markdown_block(
                f"{text1}, {text2}"
            ),
        ]
    )
    return CommandStatusChoices.STATUS_SUCCEEDED`

**Comment by jvanderaa** [comment]
Closing in favor of @smk4664 's recommendation.
