### ISSUE TITLE
Allow interaction with Nautobot in threads

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-plugin-chatops#67]
### Environment
* Nautobot version: 1.1.0
* nautobot-plugin-chatops version:  1.3.1

### Proposed Functionality

Slack provides threads for conversations, it would be cool to interact with nautobot in a slack thread

### Use Case

When troubleshooting an issue, Alert manager fires an alert in a slack channel.  The team then uses the thread from the channel to communicate about this issue and provide additional links, logs, etc for the issue.  It would be nice to have some context from Nautobot in this thread.  For now it would be cool if the team could interact with Nautobot in this thread, however I could also see some automation if an alert for a specific interface fires automatically respond in the thread with device/interface information from Nautobot.

**Comment by smk4664** [comment]
This is going to be scoped for version 2.0.

**Comment by sdoiron0330** [comment]
hey @smk4664, can you assign this to me please? thanks!

**Comment by sdoiron0330** [comment]
So, the [Slack documentation](https://api.slack.com/interactivity/slash-commands#enabling-interactivity-with-slash-commands__what-are-slash-commands) makes it pretty clear: slash commands are not available in threads.

We are, however, able to respond to an event by starting or replying within a thread.  I had a couple of ideas for how this _could_ potentially look (very rough screenshots).

Option 1) By mentioning the bot's name, we could parse the text after the mention to turn into a set of commands and display the results as normal.  We should also be able to have the existing interactive blocks if a full command isn't sent (forgetting a device name when using get-device as an example).

![image](https://user-images.githubusercontent.com/53412380/225485908-80b7653a-e32a-4a8e-88b3-5a80ff4ad4e0.png)

Option 2) We could add a "Nautobot" button within the message shortcuts that present a modal/other interactive blocks for the user to then navigate, similar to some of the preexisting subcommands.

![image](https://user-images.githubusercontent.com/53412380/225486370-f22207c6-c1e5-411a-8570-0dece7e2c6a3.png)

![image](https://user-images.githubusercontent.com/53412380/225486554-f8998f42-9007-4a56-af4d-b2659f573b64.png)

Both of these options add a new way of interacting with the bot and feel like a far step from the simple and clean slash command, so I wanted to pause and ask for opinions on if either of these options were a good direction to go in.

**Comment by smk4664** [comment]
Are both an option? As long as we keep the processing and responses the same, I like the added functionality this would provide.
