### ISSUE TITLE
Create Allow All WildCard Permissions Button

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-chatops#74]
### Proposed Functionality

Would like to see a button on the top right of access grants to have the default allow all configuration items added to the DB

### Use Case

Simplify the use of setup for those that wish to allow all.

**Comment by smk4664** [comment]
I am not sure I agree with adding the allow all to a button, I could see that as recommending the configuration for Production.  I would like to see the `Create and Add Another` button copy the command and subcommand over to the next form.
