### ISSUE TITLE
Support MySQL

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot-plugin-chatops#75]
### Proposed Functionality

Currently, Nautobot-plugin-chatops uses django.contrib.postgres.fields.ArrayField which is not compatible with MySQL Backed Database Engines.  I propose we convert this field to nautobot.utilities.fields.JSONArrayField.

### Use Case

Now that Nautobot supports MySQL, we should support MySQL as well to maintain compatibility.

**Comment by smk4664** [comment]
I will be taking up this effort.

**Comment by jvanderaa** [comment]
Thanks @smk4664

**Comment by jvanderaa** [comment]
Closed via #76
