### ISSUE TITLE
Expose a session Chatops context to improve user experience

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot-plugin-chatops#87]
### Proposed Functionality

From the Chatops point of view, that could server multiple IM integrations, it would be interesting to offer a `context` that could be used to provide per user helper information. The `dispatcher` one it's dependent on the IM platform and this one should be shared across multiple IM integrations.

For instance, defining a specific time reference to run all the commands against.

We have used it in one Chatops implementation with this simple code:

```python
"""Functions for caching per-user context."""
import hashlib
from django.core.cache import cache
from . import MyChatops

def _get_cache_key(user: str) -> str:
    """Key generator for the cache, adding the plugin prefix name."""
    key_string = "-".join([MyChatops.name, user])
    return hashlib.md5(key_string.encode("utf-8")).hexdigest()  # nosec

def get_context(user: str) -> dict:
    """Return context stored for user."""
    return cache.get(_get_cache_key(user)) or {}

def set_context(user: str, updated_context: dict) -> dict:
    """Update user context."""
    context = get_context(user)
    cache.set(_get_cache_key(user), {**context, **updated_context}, timeout=86400)
```

### Use Case

Offering a Chatops `context` would facilitate that each user would customize his experience against multiple IM, and would simplify a lot of commands using this context, because parameters can be reused.

Another example could be when you run debugging against one device, setting the device first, and then just run commands that will now via the context which is the target device.

Obviously, we should expose commands to get and set this context as needed.

**Comment by jvanderaa** [comment]
@chadell is this similar to #43? I agree that this would be good to include.

**Comment by jvanderaa** [comment]
I'm not sure that @smk4664 has been able to progress on #43 if that is the case.

**Comment by chadell** [comment]
I don't think so. This feature request is not dependent on being able to interact with multiple environments but to to offer a chatops context to the commands (that eventually can interact with multiple environments).
The `dispatcher` has a [context](https://github.com/nautobot/nautobot-plugin-chatops/blob/develop/nautobot_chatops/dispatchers/base.py#L37), where for instance the user_id is tracked , but not sure if we should extend this context with some cached data to be consumed by the plugin commands (with some methods such as `get_context` or `set_context`, or to provide another way.
Maybe, the option of extending the `dispatcher` with an extra `context` field would do the job... the point is to be able to expose the methods to update this context.
I would raise a PR to show how this could look like
